drafter:
  agent_id: ${BAND_DRAFTER_AGENT_ID}
  api_key:  ${BAND_DRAFTER_AGENT_API_KEY}


recruitment-research-agent:
  agent_id: ${RECRUITMENT_RESEARCH_AGENT_ID}
  api_key:  ${RECRUITMENT_RESEARCH_AGENT_API_KEY}

cover-letter-writer:
  agent_id: ${COVER_LETTER_WRITER_AGENT_ID}
  api_key:  ${COVER_LETTER_WRITER_API_KEY}

job-hunter:
  agent_id: ${JOB_HUNTER_AGENT_ID}
  api_key:  ${JOB_HUNTER_AGENT_API_KEY}